# Generated by Django 5.2.6 on 2025-09-21 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='teachar_conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='teacher.teacher'),
        ),
    ]
