# Generated by Django 5.2.6 on 2025-09-28 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_courses_teachar_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cour_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
