# Generated by Django 5.2.6 on 2025-10-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_courses_cour_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='cour_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
