# Generated by Django 5.2.6 on 2025-09-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=80)),
                ('stu_age', models.IntegerField()),
                ('stu_conf', models.ManyToManyField(to='teacher.courses')),
            ],
        ),
    ]
