# Generated by Django 5.2.6 on 2025-09-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_user'),
        ('teacher', '0003_alter_courses_teachar_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_conf',
            field=models.ManyToManyField(related_name='students', to='teacher.courses'),
        ),
    ]
